export const es_ar = {
  system: {
    name: "Admin-Landing",
  },
  common: {
    welcome: "Bienvenido",
    appName: "Admin Landing",
    messageWelcome: "Bienvenido al sistema de gestion de Landing",
    actions: {
      detail: "Detalles",
      edit: "Editar",
      delete: "Eliminar",
      view: "Ver",
      cancel: "Cancelar",
      save: "Guardar",
      create: "Crear",
      confirm: "Confirmar",
      add: "Agregar",
      new: "Nuevo",
      remove: "Remover",
      accept: "Aceptar",
      reject: "Rechazar",
      enter: "Ingresar",
      open: "Abrir",
      close: "Cerrar",
      back: "Volver",
      next: "Siguiente",
      continue: "Continuar",
      finally: "Finalizar",
      search: "Buscar",
      reset: "Restablecer",
      clear: "Limpiar",
      refresh: "Actualizar",
      filter: "Filtrar",
      show: "Mostrar",
      hide: "Ocultar",
      select: "Seleccionar",
      deselect: "Deseleccionar",
      upload: "Cargar",
      download: "Descargar",
      copy: "Copiar",
      paste: "Pegar",
      cut: "Cortar",
      clone: "Clonar",
      export: "Exportar",
      import: "Importar",
      selectAll: "Seleccionar todo",
      deselectAll: "Deseleccionar todo",
      more: "Más",
      readMore: "Leer más",
      info: "Información",
    },
    labels: {
      name: "Nombre",
      email: "Correo electrónico",
      phone: "Teléfono",
      date: "Fecha",
      time: "Hora",
      dateTime: "Fecha y hora",
      createdAt: "Creado en",
      updatedAt: "Actualizado en",
      status: "Estado",
      active: "Activo",
      inactive: "Inactivo",
      disabled: "Deshabilitado",
      info: "Información",
      statuses: {
        pending: "Pendiente",
        confirmed: "Confirmado",
        cancelled: "Cancelado",
        rejected: "Rechazado",
        created: "Creado",
      },
      loading: "Cargando",
      loadingRowsTable: "Cargando filas...",
      actions: "Acciones",
      action: "Acción",
      noData: "No hay datos",
      deleteMessage: "¿Estás seguro que deseas eliminar este registro?",
      deleteMessageTitle: "Eliminar registro",
      deleteMessageId: "¿Estás seguro que deseas eliminar el registro con ID: ",
    },
    validationString: {
      noEmptySpaces: "El campo no puede contener solo espacios en blanco",
      noLeadingSpaces: "El campo no puede tener espacios en blanco al inicio",
      noTrailingSpaces: "El campo no puede tener espacios en blanco al final",
      fieldRequired: "El campo es obligatorio",
      minLength: "El campo debe tener al menos {{min}} caracteres",
      maxLength: "El campo debe tener como máximo {{max}} caracteres",
      exactLength: "El campo debe tener exactamente {{exactLength}} caracteres",
      invalidEmail: "El campo debe ser un correo electrónico válido",
      invalidUrl: "El campo debe ser una URL válida",
      patternMismatch: "El campo no coincide con el patrón",
      mustBeUppercase: "El campo debe estar en mayúsculas",
      mustBeLowercase: "El campo debe estar en minúsculas",
      mustBeOneOf: "El campo debe ser uno de los siguientes valores: ",
      cannotBeOneOf: "El campo no puede ser uno de los siguientes valores: ",
      allowSpecialChars: "El campo no puede contener caracteres especiales",
      allowNumericOnly: "El campo debe contener solo números",
      invalidPhone: "El campo debe ser un número de teléfono válido",
      numericOnly: "El campo debe contener solo números",
      invalidDate: "La fecha debe ser válida",
      invalidImage: "Debe ser una imagen valida (jpg|jpeg|png|bmp|webp)",
    },
    validationNumber: {
      mustBePositive: "El campo debe ser un número positivo",
      mustBeNegative: "El campo debe ser un número negativo",
      minValue: "El campo debe ser mayor o igual a ",
      maxValue: "El campo debe ser menor o igual a ",
      lessThan: "El campo debe ser menor que ",
      moreThan: "El campo debe ser mayor que ",
      precision: "El campo debe contener {{precision}} decimales",
      mustBeInteger: "El campo debe ser un número entero",
      cannotBeZero: "El campo no puede ser cero",
      mustBeMultipleOf: "El campo debe ser un múltiplo de ",
      mustBeInRange: "El campo debe estar en el rango de ",
      invalidDecimalSeparator: "El campo debe tener un separador decimal válido",
      invalidThousandSeparator: "El campo debe tener un separador de miles válido",
    },
    errors: {
      createdError: "Error al crear",
      unknownError: "Error desconocido"
    }
  },
  toast: {
    success_add: "El registro se dió de alta correctamente.",
    success_edit: "El registro se modificó correctamente.",
    success_delete: "El registro se eliminó correctamente.",
    error_add: "Ocurrió un error al intentar agregar el registro.",
    error_edit: "Ocurrió un error al editar el registro.",
    error_delete: "Ocurrió un error al eliminar el registro.",
    copy: "Copiado al portapales!",
    title_error: "Error",
    title_success: "Exito",
    error_location: "Error al obtener la ubicación",
    error_location_message:
      "No se pudo obtener la ubicación, por favor intenta de nuevo.",
    error_update: "Ha ocurrido un error al actualizar la información",
    error: "Ha ocurrido un error",
    error_publish: "Ha ocurrido un error al publicar el servicio",
    error_get: "Ha ocurrido un error al obtener la información",
    error_update_service: "Ha ocurrido un error al actualizar el servicio",
    error_update_profile: "Ha ocurrido un error al actualizar el perfil",
    error_update_password: "Ha ocurrido un error al actualizar la contraseña",
    error_insert: "Ha ocurrido un error al guardar los datos",
    error_insert_service:
      "Ha ocurrido un error al intentar guardar el servicio",
    error_insert_profile: "Ha ocurrido un error al intentar guardar el perfil",
    error_links: "El link al que intenta acceder no existe o no es válido",
    error_load_services: "Ha ocurrido un error al cargar los servicios",
    error_load_profile: "Ha ocurrido un error al cargar el perfil",
    error_load_meetings: "Ha ocurrido un error al cargar las reuniones",
    error_load_notifications:
      "Ha ocurrido un error al cargar las notificaciones",
    error_load_feedbacks: "Ha ocurrido un error al cargar los feedbacks",
    error_permission:
      "No tienes permisos para realizar esta acción o ha ocurrido un error",
    error_validate: "Ha ocurrido un error al validar la información",
    error_checkout: "Ha ocurrido un error al contratar un servicio",
    error_load_data: "Ha ocurrido un error al cargar los datos.",
    permission_camera_denied: "Permiso de cámara denegado",
    permission_camera_bloqued: "Permiso de cámara bloqueado",
    permission_camera_denied_message:
      "Para poder usar la cámara, debes aceptar los permisos.",
    permission_camera_bloqued_message:
      "Permiso de cámara bloqueado, para acceder a la camara deberas habilitar el permiso desde la configuración de aplicaciones",
    permission_camera_limited:
      "La camara no esta disponible en este dispositivo",
    permission_location_denied: "Permiso de ubicación denegado",
    permission_location_denied_message:
      "Para poder usar la ubicación, debes aceptar los permisos.",
    permission_location_bloqued:
      "Permiso de ubicación bloqueado, para acceder a la ubicación deberas habilitar el permiso desde la configuración de aplicaciones",
    success_publish: "El servicio se publicó correctamente",
    success_update: "Tus datos fueron actualizados correctamente",
    success_update_service: "El servicio se actualizó correctamente",
    success_update_profile: "El perfil se actualizó correctamente",
    success_update_password: "La contraseña se actualizó correctamente",
    success_insert: "Los datos se guardaron correctamente",
    success_insert_service: "El servicio se guardó correctamente",
    success_delete_user: "La cuenta fue eliminada correctamente",
  },
  modules: {
    home: "Inicio",
    buttons: "Botones",
    cards: "Tarjetas",
    forms: "Formularios",
    tables: "Tablas",
    charts: "Gráficos",
    modals: "Modales",
    users: "Usuarios",
    user: "Usuario",
    organism: "Organismo",
    organisms: "Organismos",
    logs: "Logs",
    log: "Log",
    systems: "Sistemas",
    system: "Sistema",
    techs: "Técnologías",
    tech: "Técnología",
  },
  users: {
    title: "Usuarios",
    view: "Ver usuarios",
    dataUser: "Datos del usuario",
    dataPersonal: "Datos personales",
    form: {
      name: "Nombre",
      lastName: "Apellido",
      email: "Email",
      cuil: "Cuil",
      password: "Contraseña",
      confirmPassword: "Confirmar contraseña",
      phone: "Teléfono",
      role: "Rol",
      lastConnection: "Última conexión",
      enabled: "Habilitado",
      organism: "Organismo",
      system: "Sistema",
    },
  },
  device: {
    title: "Dispositivos",
    view: "Ver dispositivos",
  },
  systems: {
    title: "Sistemas",
    view: "Ver sistemas",
    enabledSystems: "Sistemas habilitados",
    form: {
      systemId: "ID del sistema",
      systemName: "Nombre del sistema",
      font: "Fuente",
      codeClientId: "ID de cliente",
      codeClientSecret: "Código secreto del cliente",
    },
    validations: {
      systemName: "El nombre del sistema es obligatorio",
      font: "La fuente es obligatoria",
    },
    messages: {
      error_system: "Ha ocurrido un error al intentar guardar el sistema",
      error_system_update:
        "Ha ocurrido un error al intentar actualizar el sistema",
    },
  },
  institution: {
    title: "Organismos",
    view: "Ver organismos",
    dataOrganism: "Datos del organismo",
    form: {
      organism: "Organismo",
      description: "Descripción",
    },
    validations: {
      organism: "El organismo es obligatorio",
      description: "La descripción es obligatoria",
    },
    messages: {
      error_organism: "Ha ocurrido un error al intentar guardar el organismo",
      error_organism_update:
        "Ha ocurrido un error al intentar actualizar el organismo",
    },
  },
  logs: {
    title: "Logs",
    view: "Ver logs",
    form: {
      date: "Fecha",
      publicIp: "IP pública",
      category: "Categoría",
      system: "Sistema",
      description: "Descripción",
    },
  },
  tech: {
    title: "Tecnologías",
    view: "Ver tecnologías",
    form: {
      name: "Nombre",
      tech: "Tecnología",
      description: "Descripción",
    },
    validations: {
      name: "El nombre es obligatorio",
    },
    messages: {
      error_tech: "Ha ocurrido un error al intentar guardar la tecnología",
      error_tech_update:
        "Ha ocurrido un error al intentar actualizar la tecnología",
    },
  },
  login: {
    common: {
      welcome_message: "¡Bienvenido a Admin-Landing! 👋🏻",
    },
    form: {
      usuario: "Nombre de Usuario",
      password: "Contraseña",
      labelCuil: "Ingrese su Nombre de usuario",
    },
    messages: {
      loginToNext: "Inicie sesión en su cuenta y comience la aventura",
      successLogin: "Sesión iniciada correctamente",
      successLogout: "Sesion cerrada",
      errorLogin: "Ha ocurrido un error al iniciar sesión",
      verifyCredentials: "Verifique sus credenciales",
      errorRegister: "Ha ocurrido un error al intentar registrarse",
      loginSuccess: "Se inicio sesion Correctamente!",
      loginError: "No se pudo iniciar sesion",

    },
  },
  heroPageInversiones: {
    title: "Portada de la Pagina de Inversiones",
    subTitle: "Configuración de la Pagina de Inversiones",
    new: "Nuevo Correo Electronico",
    edit: "Editar Sección Linea De Tiempo",
    detail: "Detalle de la Sección Linea De Tiempo",
    list: "Listado",
    form: {
      image: "Imagen",
      title: "Titulo",
      subtitle: "Sub-Titulo",

    },
    validation: {
      imageIsrequired: "La fecha es obligatoria",
      subtitleIsRequired: "El Sub-Titulo es obligatorio",
      titleIsRequired: "El titulo es obligatorio",
    },
    messages: {
      createdSuccess: "El Registro se creó correctamente",
      updatedSuccess: "El Registro se actualizó correctamente",
      deletedSuccess: "El Registro se eliminó correctamente",
      createdError: "Error al crear El Registro",
      updatedError: "Error al actualizar El Registro",
      deletedError: "Error al eliminar El Registro",
      deletedConfirm: "Esta seguro que desea eliminar el registro?",
      serverError: "Error de servidor intentelo mas tarde",
      unknownError: "Error desconocido"
    },
  },



};
